### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Tulskie** [shoujii/Next-Server-Bullseye#1]
Bei der Installation bekomme ich folgenden Fehler.

[Fr 14. Jan 16:34:49 CET 2022] Sign failed, can not get Le_LinkCert, retry time limit.
[Fr 14. Jan 16:34:49 CET 2022] {"status":"processing","expires":"2022-04-14T15:25:03Z","identifiers":[{"type":"dns","value":"pipmatz.eu"},{"type":"dns","value":"www.pipmatz.eu"}],"authorizations":["https://acme.zerossl.com/v2/DV90/authz/rGjwsvdhLTgymJ-YTVWrOQ","https://acme.zerossl.com/v2/DV90/authz/ON1s19e4qHnTM2JPwqNK9w"],"finalize":"https://acme.zerossl.com/v2/DV90/order/3jeRScGWzjAT76QixNVxkg/finalize"}
[Fr 14. Jan 16:34:49 CET 2022] _on_issue_err
[Fr 14. Jan 16:34:49 CET 2022] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Fr 14. Jan 16:34:49 CET 2022] _chk_vlist
[Fr 14. Jan 16:34:49 CET 2022] Diagnosis versions:
openssl:openssl
OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.21.4
built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
built with OpenSSL 3.0.1 14 Dec 2021
TLS SNI support enabled

Logfile:
[Fr 14. Jan 16:34:11 CET 2022] Order status is processing, lets sleep and retry.
[Fr 14. Jan 16:34:11 CET 2022] _retryafter='15'
[Fr 14. Jan 16:34:11 CET 2022] Retry after: 15
[Fr 14. Jan 16:34:27 CET 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/3jeRScGWzjAT76QixNVxkg
[Fr 14. Jan 16:34:27 CET 2022] url='https://acme.zerossl.com/v2/DV90/order/3jeRScGWzjAT76QixNVxkg'
[Fr 14. Jan 16:34:27 CET 2022] payload
[Fr 14. Jan 16:34:27 CET 2022] POST
[Fr 14. Jan 16:34:28 CET 2022] _post_url='https://acme.zerossl.com/v2/DV90/order/3jeRScGWzjAT76QixNVxkg'
[Fr 14. Jan 16:34:28 CET 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.IeJLUCX3eq '
[Fr 14. Jan 16:34:30 CET 2022] _ret='0'
[Fr 14. Jan 16:34:30 CET 2022] code='200'

Gruß Ralf

**Comment by shoujii** [comment]
Hey, das Bullseye Script ist noch nicht fertig zur Nutzung.

Vielleicht komme ich die Tage dazu das zu ändern :)

Gruß, Marcel

**Comment by Tulskie** [comment]
Schade, hätte ich gut gebrauchen können.
Danke für die Info.
Gruß Ralf

**Comment by Tulskie** [comment]
Hallo Marcel,
gibt es schon eine Vorstellung wann das Script fertig wird?
Ich würde es schon gerne wieder verwenden zumal das Buster Script nicht mehr da ist.

Gruß
Ralf

**Comment by shoujii** [comment]
Eigentlich hatte ich die Script Entwicklung aus Zeitgründen aufgegeben, aber in der letzten Zeit habe ich wieder Lust daran gefunden :)

Leider liege ich seit letzter Woche mit einer Corona Durchbruchsinfektion flach.
Mittlerweile geht es etwas besser.

Ich bin wieder dabei eine richtige Entwicklungsumgebung aufzubauen.
Eventuell habe ich den Fehler schon identifiziert.
Wenn alles gut läuft klappt wieder alles in den nächsten 2-3 Tagen

Gruß Marcel

**Comment by shoujii** [comment]
Einige Bugs sind schon gefixt. Es gibt allerdings noch ein paar Fehler.

Die 2-3 Tage sollten aber definitiv machbar sein :)

**Comment by Tulskie** [comment]
Das freut mich zu lesen,
bin gerade in Reha und nutze da meist die Zeit und baue meinen Server neu auf.
Dein Script ist mir da immer sehr dienlich. Nutze es schon seit vielen Jahren.
Ich warte dann noch die 2-3 Tage und erspare mir das manuelle doing.
Gruß
Ralf

**Comment by shoujii** [comment]
Grundsätzlich sind die Bugs soweit alle gefixt, dass die Installation bei mir zu mindestens durchläuft...

ABER ich würde das Script noch NICHT produktiv nutzen, da ich die Tage noch einige Tests vornehmen werde plus einige Settings und Configs aktualisiert werden müssen (auch der Sicherheit halber).

Welche der Addons nutzt du denn?
Teamspeak
Wordpress
Nextcloud
PHPmyadmin

Da würde ich eventuell gerne etwas verkleinern.
Zum Beispiel bin ich mir nicht sicher, ob noch allzu viele Leute Teamspeak nutzen.

Und das freut mich natürlich, wenn du das Script gerne nutzt :)

Gruß

**Comment by Tulskie** [comment]
Ich nutze PHPmyadmin und Nextcloud,
Teamspeak brauche ich nicht und mit Wordpress habe ich erst kürzlich mal reingeschaut.
Könnte vielleicht sein das ich es mal nutze.
Was mir fehlt ist OpenVpn, da ich den Server mit meinem Router verbinde.
Gruß Ralf

**Comment by shoujii** [comment]
Super, dann kann ich Teamspeak ja getrost rausnehmen und mich auf den Rest konzentrieren :)

Was VPN angeht, dass könnte ich sobald alles sinnvoll läuft nachrüsten.
Wobei es da sinnvoller wäre Wireguard zu nutzen: https://de.wikipedia.org/wiki/WireGuard
Das ist direkt im Linux Kernel integriert und schneller / sicherer und auch bei der Verwaltung einfacher.

**Comment by Tulskie** [comment]
Hab die Installation mal durchlaufen lassen,
alles okay und keine Fehler.
Wireguard ist auch möglich, hab gerade mal nachgeschaut ob der Router das unterstützt. Passt!

**Comment by shoujii** [comment]
Super!
Das freut mich wenn bei dir auch alles durchgelaufen ist.

Im Moment bin ich dabei PHPmyadmin wieder lauffähig zu machen, dass ging in letzter Zeit nicht mehr.
Da habe ich nun einen anderen Installationsweg eingefügt der weniger fehleranfällig ist.

Morgen geht das dann an die Nginx Configs (und im Nachgang nochmal Nextcloud und Wordpress), da muss einiges aktualisiert werden.
Übermorgen steht dann der Mailserver mit einigen Überarbeitungen an.

Wireguard würde ich dann wenn alles läuft implementieren. Das dürfte auch auf deinem Handy funktionieren :)

**Comment by Tulskie** [comment]
Diese Warnung hatte ich bei der Installation:
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Nginx:

**Comment by shoujii** [comment]
Der Fehler sollte jetzt hoffentlich nicht mehr auftreten :)

Ich habe das Nginx Init script getauscht.

**Comment by shoujii** [comment]
Im Moment komme ich leider bei dem Webserver / den Addons nicht weiter.

Das Script wird wohl eher nicht zeitnah fertig werden.
Es waren auch grundsätzlich sehr viele Änderungen nötig um Standardkonformer zu sein und dass das Script auf Dauer weniger fehleranfällig wird.

Gruß Marcel

**Comment by Tulskie** [comment]
Lässt sich das Script ohne die addons verwenden?
Wenigstens mit dem Mailserver?


Gruß
Ralf

Shoujii schrieb am Samstag, 29. Januar 2022 23:21:38 (+01:00):



Im Moment komme ich leider bei dem Webserver / den Addons nicht weiter.

Das Script wird wohl eher nicht zeitnah fertig werden.
Es waren auch grundsätzlich sehr viele Änderungen nötig um Standardkonformer zu sein und dass das Script auf Dauer weniger fehleranfällig wird.

Gruß Marcel

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.


-- 
Gesendet mit Vivaldi Mail. Laden Sie Vivaldi kostenlos von vivaldi.com herunter.

**Comment by shoujii** [comment]
Das sollte kein Problem sein.

Du solltest vorher nur schauen ob deine Webanwendung vollständig geht, weil es da ja gerade ein paar Probleme gibt.

Wenn es im Test geht spricht erstmal nichts dagegen.

Der Mailserver hat bei mir über Thunderbird einwandfrei funktioniert.
Du musst nur leider auf Roundcube verzichten, dazu bin ich aufgrund der Addons noch nicht gekommen.

**Comment by Tulskie** [comment]
![image](https://user-images.githubusercontent.com/46045752/151680869-e94fab70-c5f2-419d-81b1-52b14907a23a.png)
 ist mir noch aufgefallen bei der Installation.

**Comment by shoujii** [comment]
Danke für den Hinweis, das schaue ich mir morgen an.

Ich vermute er meckert, weil PCRE2 jetzt standardmäßig dabei ist und es wo anders erwartet.

Changes with nginx 1.21.5                                        28 Dec 2021

    *) Change: now nginx is built with the PCRE2 library by default.

**Comment by Tulskie** [comment]
Ich habe nochmal eine Neu Installation gemacht,
dabei habe ich folgende Fehler bekommen.
Postfix:
[OKAY] 10 checks passed!
[ERROR] 1 check/s failed! Please check /root/NeXt-Server-Bullseye/logs/failed_checks.log or consider a new installation!
[OKAY] postfix is running!
Continue (y/n)?y
Rspamd:
[OKAY] 10 checks passed!
[ERROR] 3 check/s failed! Please check /root/NeXt-Server-Bullseye/logs/failed_checks.log or consider a new installation!
failed_checks.log:
^[[1m^[[31m[ERROR]^[(B^[[m postscreen_access does NOT exist
^[[1m^[[31m[ERROR]^[(B^[[m options.inc does NOT exist
^[[1m^[[31m[ERROR]^[(B^[[m worker-normal.inc does NOT exist
^[[1m^[[31m[ERROR]^[(B^[[m worker-proxy.inc does NOT exist

Gruß Ralf

**Comment by shoujii** [comment]
Die Dateien gibt es nicht mehr und das Script meckert deshalb.

Das is in Ordnung, ich habe nur noch nicht gut Checks rausgenommen.

Heute habe ich bei dem Mailserver größere Umbauten vorgenommen.

Zusätzlich kann Roundcube nun Dateien senden.. empfangen geht noch nicht.


Gruß

**Comment by Tulskie** [comment]
Hallo Marcel,
ich habe jetzt den ganzen Abend versucht den Fehler zu beheben, aber ich komme nicht weiter.
Direkt nach der Installation kann ich meine Domain noch aufrufen , nach einem Neustart des Servers bekomme ich die Meldung:
Diese Website ist nicht erreichbar
pipmatz.de hat die Verbindung abgelehnt.

Kannst du mir da weiterhelfen?
Gruß Ralf

**Comment by shoujii** [comment]
Guten Abend Ralf,

was sagt denn der nginx Prozess?
Vielleicht geht das Initscript nicht richtig (nginx läuft nicht automatisch nach Neustart)?

Gruß Marcel

PS: ich teste es morgen, wenn ich wieder am PC bin

**Comment by Tulskie** [comment]
Boahhh,
auf die Idee wäre ich nie gekommen.
Nginx ist doch immer gestartet nach einem Neustart.
Jetzt geht es wieder, vielen Dank

**Comment by shoujii** [comment]
PPS: Schau das du bei der Installation (wenn du testen möchtest), die DEV Variante nimmst.

Sonst läufst du in die Lets Encrypt Zertifikat Limitierung, wenn du dir je Woche mehr als 5 gültige ausstellen lässt.


Zertifikate von dem Staging Sever darf man unendlich viele beziehen

**Comment by Tulskie** [comment]
Hab die Domain gewechselt, das hat auch geholfen :-)

**Comment by shoujii** [comment]
Alles klar :)

Kannst du folgende 2 Befehle testen:

systemctl enable nginx

dann rebooted und schauen ob Nginx direkt ohne Hilfe wach ist.

Und wenn das noch nicht geholfen hat:
update-rc.d nginx defaults

Und dann Rebooten?

**Comment by shoujii** [comment]
PS: wir können auch gerne via Telegram schreiben:
@Shoujii90

Das könnte hilfreich sein, wenn du möchtest.

**Comment by Tulskie** [comment]
Hab kein Telegramm,
außerdem komme ich mit dem Handy nur mühsam voran. PC-Tastatur ist da schon besser.
1. Befehl brachte keinen Erfolg
2. 2.Befehl brachte diese Fehlermeldung:
 root@mail:~# update-rc.d nginx defaults
update-rc.d: error: unable to read /etc/init.d/nginx

**Comment by shoujii** [comment]
Alles klar :)

Das wäre auch zu schön gewesen wenn die beiden Befehle geklappt hätten.
Dann schaue ich da morgen nochmal über das Init Script (https://github.com/shoujii/Next-Server-Bullseye/blob/main/configs/nginx/confs/nginx.service)

Eigentlich sollte das dafür sorgen dass Nginx nach einem Neustart läuft.

Danke dir für das fleißige testen!
Ohne Helfer kann ich kaum alles testen.

Gruß Marcel

**Comment by shoujii** [comment]
Guten Morgen,

Ich hatte es eben getestet und vor dem Reboot:
`systemctl enable nginx.service `
eingegeben und er hat einen Symlink (Verknüpfung) erstellt.

Nach dem Reboot war die Webseite erreichbar.
Den Befehl habe ich jetzt in das Script integriert.
Falls du es schaffst, kannst du ja schauen, ob es bei dir nun direkt geht nach einer neuen Installation.

Zum Testen kann ich dir den "Install dev mode [git]:" ans Herz legen, so kannst du das Lets Encrypt Zertifikat Limit umgehen und die Installation geht schneller (er erzeugt kürzere Diffie-Hellman Schlüssel).
Du musst dann allerdings einmalig die Staging Zertifikate deinem genutztem Browser hinzufügen:
https://letsencrypt.org/docs/staging-environment/

Die Intermediate Certificates:
["(STAGING) Artificial Apricot R3"](https://letsencrypt.org/certs/staging/letsencrypt-stg-int-r3.pem)
["(STAGING) Ersatz Edamame E1"](https://letsencrypt.org/certs/staging/letsencrypt-stg-int-e1.pem)

und die Root Certificates:
["(STAGING) Pretend Pear X1"](https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem)
["(STAGING) Bogus Broccoli X2"](https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x2.pem)

**Comment by Tulskie** [comment]
Moin,
Ich werde es heute Nachmittag testen und gebe dir dann Bescheid.

**Comment by Tulskie** [comment]
Hallo Marcel,
das sieht gut aus.
Die Website bleibt auch nach mehreren Neustarts erreichbar.
root@mail:~# ps -e
  PID TTY          TIME CMD
 1097 ?        00:00:00 nginx
 1098 ?        00:00:00 nginx
 1099 ?        00:00:00 nginx
 1100 ?        00:00:00 nginx
 1101 ?        00:00:00 nginx
Der Service läuft.

**Comment by shoujii** [comment]
Super das freut mich :)
Nach und nach werden es weniger Bugs!

Der einzige richtige große Showstopper ist Roundcube…
Hoffebt habe ich da bald eine Eingebung.

Ansonsten funktioniert ja alles / es sind nur wenige kleine Bugs die keine großen Auswirkungen haben.

**Comment by Tulskie** [comment]
Hallo Marcel,
ich konnte bis jetzt keine Störung mehr finden. Alles scheint zu laufen.
Ich nehme den Server jetzt wieder in Betrieb.
Solltest du noch jemanden für einen Test benötigen, lass es mich wissen.

Besten Dank für deine Arbeit.
Gruß Ralf

**Comment by shoujii** [comment]
Hallo Ralf,

das freut mich zu hören :)
Dann wünsche ich dir viel Spaß mit dem Server!
Den Fehlerbericht mache ich nun zu, wenn noch etwas ist kannst du gerne einen neuen öffnen.

Gruß Marcel
