### ISSUE TITLE
Postfix

### ISSUE THREAD

**Issue by Tulskie** [shoujii/Next-Server-Bullseye#8]
Hallo Marcel,
Bei der Installation bekomme ich einen Fehler bei systemctl reload postfix.
Postfix nicht vorhanden/gestartet oder so ähnlich.
Dann bricht die Installation ab.
Gruß

**Comment by shoujii** [comment]
Das sollte mit dem Commit wieder gehen :) https://github.com/shoujii/Next-Server-Bullseye/commit/b5ee0537d5721d99cd438dc538fb3f2b1838ea1a 

Gruß

**Comment by Tulskie** [comment]
Leider nicht.
Folgende Fehlermeldung bekomme ich:
postfix.service is not active, cannot reload.
An error occurred in line 40 of file /root/NeXt-Server-Bullseye/script/postfix.sh:
systemctl reload postfix

Gruß

**Comment by shoujii** [comment]
Geht es jetzt wieder?

**Comment by Tulskie** [comment]
Alles Tippie Toppie,
ohne Probleme durchgelaufen.
Danke

**Comment by shoujii** [comment]
Closed :)
